version: '3'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_container
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  data_ingestor: 
    image: python:3.12
    container_name: python_ingestor_container
    volumes:
      - .:/app  # mapeia a pasta 'infra' pra pasta '/app' no container
    working_dir: /app # define o diretório de trabalho para o container
    command: sh -c "pip install influxdb-client && python sensor-influx_bridge.py"
    depends_on:
      - influxdb
   
volumes:
  influxdb_data:
  grafana_data: